// TODO: Replace mock imports with real SSE data from useCrisisStream
import type { ResponsePlan, PlanLineItem, SourceOption } from './types';

export const MOCK_PLANS: ResponsePlan[] = [
  {
    name: 'fastest',
    strategy: 'Minimize delivery time by prioritizing local Philadelphia suppliers with same-day or next-day capacity',
    line_items: [
      {
        source_id: 'src-001',
        supplier_name: 'Philabundance Warehouse',
        food_category: 'protein',
        item_name: 'Frozen Chicken Breast',
        quantity_lbs: 3200,
        cost: 4480.0,
        lead_time_days: 1,
      },
      {
        source_id: 'src-002',
        supplier_name: 'Chester County Food Bank',
        food_category: 'produce',
        item_name: 'Fresh Mixed Vegetables',
        quantity_lbs: 2500,
        cost: 3250.0,
        lead_time_days: 1,
      },
      {
        source_id: 'src-003',
        supplier_name: 'Share Food Program',
        food_category: 'grains',
        item_name: 'Rice (25lb bags)',
        quantity_lbs: 4000,
        cost: 2800.0,
        lead_time_days: 2,
      },
      {
        source_id: 'src-004',
        supplier_name: 'Bucks County Opportunity Council',
        food_category: 'canned',
        item_name: 'Canned Beans',
        quantity_lbs: 1800,
        cost: 1920.0,
        lead_time_days: 2,
      },
    ] satisfies PlanLineItem[],
    total_cost: 12450.0,
    coverage_pct: 85,
    max_lead_time_days: 2,
    estimated_people_served: 15000,
  },
  {
    name: 'cheapest',
    strategy: 'Minimize total cost using bulk USDA commodity channels and donated inventory from regional partners',
    line_items: [
      {
        source_id: 'src-005',
        supplier_name: 'USDA TEFAP Distribution',
        food_category: 'protein',
        item_name: 'Canned Chicken',
        quantity_lbs: 2800,
        cost: 1400.0,
        lead_time_days: 5,
      },
      {
        source_id: 'src-006',
        supplier_name: 'Feeding America Eastern PA',
        food_category: 'grains',
        item_name: 'Bulk Pasta',
        quantity_lbs: 3500,
        cost: 1750.0,
        lead_time_days: 3,
      },
      {
        source_id: 'src-007',
        supplier_name: 'Montgomery County Food Bank',
        food_category: 'canned',
        item_name: 'Canned Soup Variety',
        quantity_lbs: 2200,
        cost: 1980.0,
        lead_time_days: 4,
      },
      {
        source_id: 'src-003',
        supplier_name: 'Share Food Program',
        food_category: 'dairy',
        item_name: 'Shelf-stable Milk',
        quantity_lbs: 1500,
        cost: 1350.0,
        lead_time_days: 3,
      },
      {
        source_id: 'src-008',
        supplier_name: 'Delaware Valley Food Council',
        food_category: 'produce',
        item_name: 'Canned Vegetables',
        quantity_lbs: 1800,
        cost: 1720.0,
        lead_time_days: 4,
      },
    ] satisfies PlanLineItem[],
    total_cost: 8200.0,
    coverage_pct: 78,
    max_lead_time_days: 5,
    estimated_people_served: 12000,
  },
  {
    name: 'best_nutrition',
    strategy: 'Maximize nutritional diversity with fresh produce, lean protein, and dairy from premium regional suppliers',
    line_items: [
      {
        source_id: 'src-009',
        supplier_name: 'Lancaster Farm Fresh Cooperative',
        food_category: 'produce',
        item_name: 'Fresh Seasonal Produce Mix',
        quantity_lbs: 4500,
        cost: 5850.0,
        lead_time_days: 2,
      },
      {
        source_id: 'src-010',
        supplier_name: 'Philly Protein Partners',
        food_category: 'protein',
        item_name: 'Lean Ground Turkey',
        quantity_lbs: 2800,
        cost: 4480.0,
        lead_time_days: 3,
      },
      {
        source_id: 'src-011',
        supplier_name: 'Dairy Farmers of SE Pennsylvania',
        food_category: 'dairy',
        item_name: 'Fresh Milk & Yogurt',
        quantity_lbs: 2000,
        cost: 2600.0,
        lead_time_days: 2,
      },
      {
        source_id: 'src-012',
        supplier_name: 'Whole Grain Distributors NE',
        food_category: 'grains',
        item_name: 'Whole Wheat Bread',
        quantity_lbs: 1500,
        cost: 1870.0,
        lead_time_days: 4,
      },
    ] satisfies PlanLineItem[],
    total_cost: 14800.0,
    coverage_pct: 92,
    max_lead_time_days: 4,
    estimated_people_served: 18000,
  },
];

export const MOCK_SOURCES: SourceOption[] = [
  {
    id: 'src-001',
    supplier_name: 'Philabundance Warehouse',
    food_category: 'protein',
    item_name: 'Frozen Chicken Breast',
    quantity_available_lbs: 5000,
    unit_cost_per_lb: 1.4,
    lead_time_days: 1,
    reliability_score: 0.95,
    source_type: 'database',
    notes: 'Primary Philadelphia food bank warehouse. Consistent supply.',
  },
  {
    id: 'src-003',
    supplier_name: 'Share Food Program',
    food_category: 'grains',
    item_name: 'Rice (25lb bags)',
    quantity_available_lbs: 8000,
    unit_cost_per_lb: 0.7,
    lead_time_days: 2,
    reliability_score: 0.9,
    source_type: 'database',
    notes: 'Largest hunger relief organization in Philadelphia region.',
  },
  {
    id: 'src-005',
    supplier_name: 'USDA TEFAP Distribution',
    food_category: 'protein',
    item_name: 'Canned Chicken',
    quantity_available_lbs: 10000,
    unit_cost_per_lb: 0.5,
    lead_time_days: 5,
    reliability_score: 0.85,
    source_type: 'database',
    notes: 'Federal commodity program. Requires advance request paperwork.',
  },
  {
    id: 'src-006',
    supplier_name: 'Feeding America Eastern PA',
    food_category: 'grains',
    item_name: 'Bulk Pasta',
    quantity_available_lbs: 6000,
    unit_cost_per_lb: 0.5,
    lead_time_days: 3,
    reliability_score: 0.88,
    source_type: 'database',
    notes: 'Regional Feeding America affiliate with bulk dry goods.',
  },
  {
    id: 'src-009',
    supplier_name: 'Lancaster Farm Fresh Cooperative',
    food_category: 'produce',
    item_name: 'Fresh Seasonal Produce Mix',
    quantity_available_lbs: 6000,
    unit_cost_per_lb: 1.3,
    lead_time_days: 2,
    reliability_score: 0.82,
    source_type: 'web_search',
    notes: 'Found via Tavily search. Lancaster County farm co-op with surplus capacity.',
  },
  {
    id: 'src-010',
    supplier_name: 'Philly Protein Partners',
    food_category: 'protein',
    item_name: 'Lean Ground Turkey',
    quantity_available_lbs: 4000,
    unit_cost_per_lb: 1.6,
    lead_time_days: 3,
    reliability_score: 0.78,
    source_type: 'web_search',
    notes: 'Found via Tavily search. Local protein distributor with emergency allocation.',
  },
];
